app:
  build: .
web:
  extends:
    service: app
  command: gunicorn -b 0.0.0.0:8000 --reload measurements.wsgi --workers 4 --timeout 120
  links:
  - redis
  - rabbitmq

redis:
  image: redis:3.2

rabbitmq:
  image: rabbitmq:3.6

worker:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery worker -l info
  links:
    - redis
    - rabbitmq

beat:
  extends:
    service: app
  command: celery -A measurements.runcelery.celery beat -l info
  links:
    - redis
    - rabbitmq
